name: Publish to NPM

on:
  push:
    tags:
      - 'v*.*.*'  # This will trigger the workflow when a new version tag (e.g., v1.0.0) is pushed.

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Specify your Node.js version
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm test

    - name: Publish to NPM
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish

    - name: Tag release
      if: github.ref == 'refs/tags/' && github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"
        git fetch --tags
        PACKAGE_VERSION=$(node -p "require('./package.json').version")
        git tag -a "v${PACKAGE_VERSION}" -m "Release version ${PACKAGE_VERSION}"
        git push origin --tags
